name: Test Bot BĐS
on:
  workflow_dispatch: {} # Cho phép bạn bấm nút chạy thủ công

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install curl_cffi beautifulsoup4
      - run: python test_bds.py
